### ISSUE TITLE
Смещенные надписи в графике скоростей

### ISSUE THREAD

**Issue by mangoozt** [Dostoyewski/KTViz#1]
![image](https://user-images.githubusercontent.com/15967850/81793188-b0b73200-9511-11ea-8d6f-f0ef70c3eb46.png)

**Comment by Dostoyewski** [comment]
Как лучше их разместить, чтобы читабельно было?

**Comment by mangoozt** [comment]
Вообще убрать подписи

**Comment by Dostoyewski** [comment]
Исправлено в коммите 9ad4039d
